/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenlab;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Lourdes Zamora
 */
public class JuegoPeleas extends javax.swing.JFrame {
 
    /**
     * Creates new form JuegoPeleas
     */
    public JuegoPeleas() {
        initComponents();
    }
    int op=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnatacar1 = new javax.swing.JButton();
        btnatacar = new javax.swing.JButton();
        btncurar1 = new javax.swing.JButton();
        btncurar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        vidapikachu = new javax.swing.JProgressBar();
        vidacharmander = new javax.swing.JProgressBar();
        vidahitmonchan = new javax.swing.JProgressBar();
        vidadewgon = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Charmander_XY.gif"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(42, 42));
        jLabel1.setMinimumSize(new java.awt.Dimension(42, 42));
        jLabel1.setPreferredSize(new java.awt.Dimension(48, 52));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 290, 48, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dewgong_XY_variocolor.gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(750, 300, 90, 69);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/charmander.gif"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 10, 40, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/day_10__hitmonchan_by_ladydeven-d8hfs4r.gif"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(650, 0, 50, 50);

        btnatacar1.setText("ATACAR");
        btnatacar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnatacar1MouseClicked(evt);
            }
        });
        getContentPane().add(btnatacar1);
        btnatacar1.setBounds(60, 180, 100, 23);

        btnatacar.setText("ATACAR");
        btnatacar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnatacarMouseClicked(evt);
            }
        });
        getContentPane().add(btnatacar);
        btnatacar.setBounds(820, 170, 100, 23);

        btncurar1.setText("CURARSE");
        btncurar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btncurar1MousePressed(evt);
            }
        });
        getContentPane().add(btncurar1);
        btncurar1.setBounds(60, 230, 100, 23);

        btncurar.setText("CURARSE");
        btncurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btncurarMousePressed(evt);
            }
        });
        getContentPane().add(btncurar);
        btncurar.setBounds(820, 220, 100, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pikachu_BW.gif"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 50, 40, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dewgong.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(660, 50, 50, 50);

        vidapikachu.setValue(100);
        getContentPane().add(vidapikachu);
        vidapikachu.setBounds(80, 70, 170, 20);

        vidacharmander.setValue(100);
        getContentPane().add(vidacharmander);
        vidacharmander.setBounds(80, 20, 170, 20);

        vidahitmonchan.setValue(100);
        getContentPane().add(vidahitmonchan);
        vidahitmonchan.setBounds(710, 10, 170, 20);

        vidadewgon.setValue(100);
        getContentPane().add(vidadewgon);
        vidadewgon.setBounds(710, 70, 170, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hitmonchan_XY.gif"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(680, 270, 60, 90);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pikachu_XY_variocolor.gif"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 290, 70, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo_Gimnasio_Azalea.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 930, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnatacarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnatacarMouseClicked
        // TODO add your handling code here:
        if (op==0){
        Random rand=new Random();
        String ataque=" ",atacante=" ",atacados=" ";
        int opcionp=rand.nextInt(2)+1;
        int opciona=rand.nextInt(2)+1;
        String atacado="PC";
        char lastimado=atacado.charAt(opcionp-1);
        
        switch(opcionp){
            case 1:
                atacante="DEWGONG";
                switch(opciona){
                    case 1:
                        ataque="Golpe de Cuerpo";
                         switch(lastimado){
                             case 'P':
                                 vidapikachu.setValue((int)(vidapikachu.getValue()-vidapikachu.getValue()*0.50));
                                 atacados="PIKACHU";
                             break;
                             case 'C':
                                 vidacharmander.setValue((int)(vidacharmander.getValue()-vidacharmander.getValue()*0.45));
                                 atacados="CHARMANDER";
                                 break;
                            }
                    break;
                        
                    default:
                        ataque="Rayo de hielo";
                         switch(lastimado){
                             case 'P':
                                 atacados="PIKACHU";
                                 vidapikachu.setValue((int)(vidapikachu.getValue()-vidapikachu.getValue()*0.26));
                             break;
                             case 'C':
                                 atacados="CHARMANDER";
                                 vidacharmander.setValue((int)(vidacharmander.getValue()-vidacharmander.getValue()*0.05));
                         break;   
                         }
                    break;
                }
            break;
              //HITMONCHAN 
            default:
                atacante="HITMNCHAN";
                  switch(opciona){
                    case 1:
                        ataque="Puño de bala";
                         switch(lastimado){
                             case 'P':
                                 atacados="PIKACHU";
                                 vidapikachu.setValue((int)(vidapikachu.getValue()-vidapikachu.getValue()*0.50));
                             break;
                             case 'C':
                                 atacados="CHARMANDER";
                                 vidacharmander.setValue((int)(vidacharmander.getValue()-vidacharmander.getValue()*0.50));
                         break;
                         }
                    break;
                        
                    default:
                        ataque="MEGA PUÑO";
                         switch(lastimado){
                             case 'P':
                                 atacados="PIKACHU";
                                 vidapikachu.setValue((int)(vidapikachu.getValue()-vidapikachu.getValue()*0.15));
                             break;
                             case 'C':
                                 atacados="CHARMANDER";
                                 vidacharmander.setValue((int)(vidacharmander.getValue()-vidacharmander.getValue()*0.15));
                         break;   
                         }
                    break;
                }
            break;    
                }
        if(vidapikachu.getValue()<=0||vidacharmander.getValue()<=0){
            JOptionPane.showMessageDialog(null,"El equipo de DEWGONG Y HITMONCHAN A GANADO");
        }else if(vidadewgon.getValue()<=0||vidahitmonchan.getValue()<=0){
            JOptionPane.showMessageDialog(null,"El equipo de PIKACHU Y CHARMANDER A GANADO");
        }
        JOptionPane.showMessageDialog(null,ataque+" DE: "+atacante+" A: "+atacados);
        op=1;
        }
        
    }//GEN-LAST:event_btnatacarMouseClicked

    private void btnatacar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnatacar1MouseClicked
        // TODO add your handling code here:
        if (op==1){
        Random rand=new Random();
        String ataque=" ",atacante=" ",atacados=" ";
        int opcionp=rand.nextInt(2)+1;
        int opciona=rand.nextInt(2)+1;
        String atacado="DH";
        char lastimado=atacado.charAt(opcionp-1);
        
        switch(opcionp){
            case 1:
                atacante="PIKACHU";
                switch(opciona){
                    case 1:
                        ataque="Impactrueno";
                         switch(lastimado){
                             case 'D':
                                 vidadewgon.setValue((int)(vidadewgon.getValue()-vidadewgon.getValue()*0.25));
                                 atacados="DEWONG";
                             break;
                             case 'H':
                                 vidahitmonchan.setValue((int)(vidahitmonchan.getValue()-vidahitmonchan.getValue()*0.25));
                                 atacados="HITMONCHAN";
                                 break;
                            }
                    break;
                        
                    default:
                        ataque="Latigo";
                         switch(lastimado){
                             case 'D':
                                 atacados="DEWONG";
                                 vidadewgon.setValue((int)(vidadewgon.getValue()-vidadewgon.getValue()*0.25));
                             break;
                             case 'H':
                                 atacados="HITMONCHAN";
                                 vidahitmonchan.setValue((int)(vidahitmonchan.getValue()-vidahitmonchan.getValue()*0.25));
                         break;   
                         }
                    break;
                }
            break;
              //HITMONCHAN 
            default:
                opciona=rand.nextInt(3)+1;
                atacante="CHAMANDER";
                  switch(opciona){
                    case 1:
                        ataque="Furia Dragon";
                         switch(lastimado){
                             case 'D':
                                 atacados="DEWONG";
                                 vidadewgon.setValue((int)(vidadewgon.getValue()-vidadewgon.getValue()*0.50));
                             break;
                             case 'H':
                                 atacados="HITMONCHAN";
                                 vidahitmonchan.setValue((int)(vidahitmonchan.getValue()-vidahitmonchan.getValue()*0.50));
                         break;
                         }
                    break;
                    case 2:
                        ataque="Lanza Llamas";
                    switch(lastimado){
                             case 'D':
                                 atacados="DEWONG";
                                 vidadewgon.setValue((int)(vidadewgon.getValue()-vidadewgon.getValue()*0.10));
                             break;
                             case 'H':
                                 atacados="HITMONCHAN";
                                 vidahitmonchan.setValue((int)(vidahitmonchan.getValue()-vidahitmonchan.getValue()*0.10));
                         break;
                         }
                    break;
                    default:
                        ataque="INFIERNO";
                         switch(lastimado){
                             case 'D':
                                 atacados="DEWONG";
                                 vidadewgon.setValue((int)(vidadewgon.getValue()-vidadewgon.getValue()*0.30));
                             break;
                             case 'H':
                                 atacados="HITMONCHAN";
                                 vidahitmonchan.setValue((int)(vidahitmonchan.getValue()-vidahitmonchan.getValue()*0.30));
                         break;   
                         }
                    break;
                }
            break;    
                }
        if(vidapikachu.getValue()<=0||vidacharmander.getValue()<=0){
            JOptionPane.showMessageDialog(null,"El equipo de DEWGONG Y HITMONCHAN A GANADO");
        }else if(vidadewgon.getValue()<=0||vidahitmonchan.getValue()<=0){
            JOptionPane.showMessageDialog(null,"El equipo de PIKACHU Y CHARMANDER A GANADO");
        }
        JOptionPane.showMessageDialog(null,ataque+" DE: "+atacante+" A: "+atacados);
        op=0;
        }
       
        
    }//GEN-LAST:event_btnatacar1MouseClicked

    private void btncurarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncurarMousePressed
        // TODO add your handling code here:
        if (op==1){
        Random rand= new Random();
        int i=rand.nextInt(2)+1;
        switch(i){
            case 1:
                vidadewgon.setValue((int)(vidadewgon.getValue()+vidadewgon.getValue()*0.03));
            break;
            default:
                vidahitmonchan.setValue((int)(vidadewgon.getValue()+vidadewgon.getValue()*0.05));
            break;
        }
        op=0;
        }
        
    }//GEN-LAST:event_btncurarMousePressed

    private void btncurar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncurar1MousePressed
        // TODO add your handling code here:
        if (op==0){
        Random rand= new Random();
        int i=rand.nextInt(2)+1;
        switch(i){
            case 1:
                vidadewgon.setValue((int)(vidadewgon.getValue()+vidadewgon.getValue()*0.03));
            break;
            default:
                vidahitmonchan.setValue((int)(vidadewgon.getValue()+vidadewgon.getValue()*0.05));
            break;
        }
        op=1;
        }
    }//GEN-LAST:event_btncurar1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoPeleas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoPeleas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoPeleas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoPeleas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoPeleas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatacar;
    private javax.swing.JButton btnatacar1;
    private javax.swing.JButton btncurar;
    private javax.swing.JButton btncurar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar vidacharmander;
    private javax.swing.JProgressBar vidadewgon;
    private javax.swing.JProgressBar vidahitmonchan;
    private javax.swing.JProgressBar vidapikachu;
    // End of variables declaration//GEN-END:variables
}
